# Generated by Django 3.1.2 on 2020-10-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_end_point', models.CharField(max_length=50, unique=True)),
                ('miles', models.PositiveIntegerField()),
                ('difficulty', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
                ('stops', models.CharField(default='SOME STRING', max_length=200)),
            ],
        ),
    ]
