# Generated by Django 3.1.2 on 2020-10-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='London_Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_end_point', models.CharField(max_length=50)),
                ('miles', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
