# Generated by Django 3.1.2 on 2020-10-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('london_routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='london_route',
            name='stops',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='london_route',
            name='miles',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
