# Generated by Django 3.1.2 on 2020-10-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('london_routes', '0002_auto_20201021_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='london_route',
            name='miles',
            field=models.PositiveIntegerField(),
        ),
    ]
